### ISSUE TITLE
Refreshing doesn't work as you would expect.

### ISSUE THREAD

**Issue by cgarvis** [gaearon/flux-react-router-example#14] opened 2015-01-14 21:04 UTC
Going to http://gaearon.github.io/flux-react-router-example/#/cgarvis redirects to http://gaearon.github.io/flux-react-router-example/#/gaearon

**Comment by gaearon** [comment] 2015-01-14 21:53
Can you give more exact steps to reproduce the problem?

Do you see this locally or on hosted example? I can't repro.

Maybe you're hitting Enter too fast and input box grabs the focus? I should probably remove autofocus when we're on a user page..

**Comment by cgarvis** [comment] 2015-01-14 22:31
Search for someone other than yourself and then refresh the page.

**Comment by cgarvis** [comment] 2015-01-14 22:32
Hmm didn't work on my Mac but works on my phone.  I'll see if I can reproduce tonight on my computerr

**Comment by gaearon** [comment] 2015-01-14 22:46
Do you have Windows Phone by chance?

**Comment by gaearon** [comment] 2015-01-26 17:23
Closing this out since I can't reproduce.
Let me know if you find a repro!

Could also be related to https://github.com/rackt/react-router/issues/586 which has been fixed upstream.

**Closed by gaearon** 2015-01-26 17:23 UTC

**Comment by cridenour** [comment] 2015-01-26 19:49
I can reproduce.

Click on the original link in this issue, then click in the URL bar and hit enter. (Applies to any "user" page)

**Comment by gaearon** [comment] 2015-01-26 21:23
Thanks, I see that now!
Fixed by removing autofocus completely.
